### ISSUE TITLE
Пригласить меня в коллабораторы

### ISSUE THREAD

**Issue by justjune** [GreatBIA/university_u3d#1]
Подписать проект, чтобы мне не нужно было искать: Кто автор?
Если нужна проверка, писать запрос в Issues, с назначением задания мне.
Аналогично для других репозиториев.

**Comment by dedalus-3** [comment]
Автор: Баранов Иван МХ-401.
Проект вроде бы подписан или нужно как-то иначе написать?

**Comment by justjune** [comment]
Я предлагал файл, названный именем автора размещать в папке проекта - тогда сразу видно. Кроме этого, приглашений на проверку так и не было. Как мне догадаться, что работа готова?

**Comment by dedalus-3** [comment]
По поводу файла, просто указать в README кто автор?
По поводу проверки, еще не просил, так как работу довожу до конца. Как только закончу, то отправлю запрос.

**Comment by justjune** [comment]
Да, можно там. Доделывайте!

**Comment by dedalus-3** [comment]
Сергей Иванович, подскажите еще раз, вот я внес изменения в репозиторий, что я должен сделать, чтобы Вам пришло уведомление?

**Comment by justjune** [comment]
Пишете issue и в Assignes выбираете меня.
